### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [wbrenna/GTFSOffline#16]
A Submissions Queue thread has been created for it: https://f-droid.org/forums/topic/grtransit-android-app/

**Comment by wbrenna** [comment]
Thanks! Just to correct the record, the two apps are substantially different. I should clarify this on the main page - GRTransit has a larger feature set and specifies only to the GRT provider. This app is very privacy centric (no Google Analytics, no internet permissions) and supports many transit providers, with the caveat that the user probably needs to process the GTFS files themselves. I would suggest that they both be queued to F-Droid!

**Comment by homlett** [comment]
Done!
https://gitlab.com/fdroid/rfp/issues/12

**Comment by wbrenna** [comment]
Thanks!
