### ISSUE TITLE
[FR] Centro database

### ISSUE THREAD

**Issue by jnytucep** [wbrenna/GTFSOffline#17]
Would it be possible to add the [Centro](http://www.centro.org/CentroGTFS/CentroGTFS.zip) system to your database [list](http://wbrenna.ca/gdrivefilelist.txt)? My attempts to create a db were unsuccessful.

**Comment by wbrenna** [comment]
I gave it a shot. Not sure if it'll auto update but it seemed to work on my device.

**Comment by jnytucep** [comment]
Thanks! I did manage to figure out how to process the db locally, but hopefully this will help others in the future.
