### ISSUE TITLE
rtd denver

### ISSUE THREAD

**Issue by rosc2112** [wbrenna/GTFSOffline#21]
greetings. I've been trying to get rtd denver's gtfs data to work, but it's not. dunno where to begin to figure out why not, since i'm quite new to android, although my phone is not: this is in a zte n817 running android v4.4.4.x. Hoping a kind programmer might take a look at rtd's data and clue me in whether the fault is theirs, mine or other :)
thanks in advance. rtd's gtfs page is here
http://www.rtd-denver.com/gtfs-developer-guide.shtml

**Comment by wbrenna** [comment]
Can you give the output when you run the mksql processing script on the GTFS data?

**Comment by rosc2112** [comment]
sorry for the delay. From my linux box (debian wheezy, asus eeepc 900a)

~/work/save/zten817/gtfs$ ./mksql3db.sh rtd data/*.txt using database version 3 data/agency.txt data/calendar_dates.txt data/calendar.txt data/feed_info.txt data/routes.txt data/shapes.txt data/stops.txt data/stop_times.txt data/trips.txt Checking for missing calendar_dates.txt or calendar.txt... Creating indices... Indices created. Renaming and cleaning up... rtd: 78.6% -rw------- 1 rosc rosc 71528448 May 2 23:39 rtd -rw------- 1 rosc rosc 15325980 May 2 23:41 rtd.gz -rw------- 1 rosc rosc 40 May 2 23:41 rtd.version 3 14.6 6fc951643be392929d68517129b282a5 
----

**Comment by rosc2112** [comment]
Eureka! I found the problem - user error! :p

didn't know ya have to go back into settings and select the db :) 

thanks much for the mucho useful app
-hug a developer today :)
